id: P003159
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:44:15.543405
source_metadata:
  id: bdr:W3CN5249
  title: དཔལ་བསམ་ཡས་གཙུག་ལག་ཁང་ཆེན་མོའི་ཞལ་འདོན་གཅེས་བསྡུས་ཐར་ལམ་གསལ་སྒྲོན།
  author: ''
  volumes:
    0887d7ad335d4b1290de2829d812ccf5:
      image_group_id: I3CN5251
      title: ''
      volume_number: 1
      total_pages: 572
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
