id: I790A1944
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:32:42+00:00'
last_modified: '2022-06-07T17:59:23.916574+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5249
  title: དཔལ་བསམ་ཡས་གཙུག་ལག་ཁང་ཆེན་མོའི་ཞལ་འདོན་གཅེས་བསྡུས་ཐར་ལམ་གསལ་སྒྲོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7B31:
      image_group_id: I3CN5251
      title: ''
      total_pages: 572
      order: 1
      base_file: 7B31.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
